services:
  # djangoapp:
  #   container_name: ${CONTAINER_BACKEND_NAME}
  #   build:
  #     context: .
  #   ports:
  #     - 1404:1404
  #   volumes:
  #     - .:/app
  #   restart: always
  #   depends_on:
  #     - db
  db:
    env_file: '.env'
    container_name: ${CONTAINER_DB_NAME}
    image: postgres:17
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: