services:
  djangoapp:
    container_name: ${CONTAINER_BACKEND_NAME}
    build:
      context: .
    ports:
      - 1404:1404
    volumes:
      - .:/app
      - ./freitascodes/static:/app/freitascodes/static
    restart: always
    depends_on:
      - db
    links:
      - db:db
    networks:
      - freitascodesnetwork
  db:
    env_file: '.env'
    container_name: ${CONTAINER_DB_NAME}
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - freitascodesnetwork
volumes:
  postgres_data:
  
networks:
  freitascodesnetwork:
    driver: bridge