services:
  djangoapp:
    container_name: ${CONTAINER_BACKEND_NAME}
    build:
      context: .
    ports:
      - 1404:1404
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db
    env_file: '.env'

  db:
    env_file: '.env'
    container_name: ${CONTAINER_DB_NAME}
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: