services:
  db:
    env_file: '.env'
    container_name: ${CONTAINER_DB_NAME}
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: