services:
  djangoapp:
    container_name: ${CONTAINER_BACKEND_NAME}
    build:
      context: .
    ports:
      - 1404:1404
    volumes:
      - .:/app
      - static_data:/app/freitascodes/static
    restart: always
    depends_on:
      - db
    links:
      - db:db
    networks:
      - freitascodesnetwork
  db:
    env_file: '.env'
    container_name: ${CONTAINER_DB_NAME}
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - freitascodesnetwork
  nginx:
    image: nginx:latest
    container_name: ${CONTAINER_NGINX_NAME}
    volumes:
      - static_data:/usr/share/nginx/html/static
      - ./nginx.conf:/etc/nginx/nginx.conf/
    ports:
      - "80:80"
    depends_on:
      - djangoapp
    networks:
      - freitascodesnetwork
volumes:
  postgres_data:
  static_data:
  
networks:
  freitascodesnetwork:
    driver: bridge