from freitascodes.serializers.TipoStacksSerializer import TipoStacksSerializer
from freitascodes.serializers.StacksSerializer import StacksSerializer
from freitascodes.serializers.ProjetosSerializer import ProjetosSerializer
from freitascodes.serializers.CertificadosSerializer import CertificadosSerializer