from freitascodes.admin.TipoStacksAdmin import TipoStacksAdmin
from freitascodes.admin.StacksAdmin import StacksAdmin
from freitascodes.admin.ProjetosAdmin import ProjetosAdmin
from freitascodes.admin.CertificadosAdmin import CertificadosAdmin
from freitascodes.admin.ImagensAdmin import ImagensAdmin