# Generated by Django 5.1.3 on 2024-11-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Tecnologia')),
                ('stack_type', models.IntegerField(choices=[(1, 'Linguagem de Programação'), (2, 'Framework'), (3, 'Biblioteca')], default=1, verbose_name='Tipo de Stack')),
                ('skillicon_name', models.CharField(help_text='Disponível em https://github.com/tandpfun/skill-icons?tab=readme-ov-file#icons-list', verbose_name='Name do Skill Icon')),
            ],
            options={
                'verbose_name': 'Stack',
                'verbose_name_plural': 'Stacks',
                'ordering': ['stack_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Projeto')),
                ('project_type', models.IntegerField(choices=[(1, 'Projeto'), (2, 'Biblioteca')], default=1, verbose_name='Tipo de Projeto')),
                ('repo_name', models.CharField(help_text='Link do Github', max_length=500, verbose_name='Name do Repositório')),
                ('avaliable_at', models.CharField(help_text='Link do Projeto em produção ou biblioteca no PYPI por exemplo.', max_length=500, verbose_name='Disponível em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está Disponível?')),
                ('stacks', models.ManyToManyField(help_text='Stacks utilizadas ou disponível para estas stacks', to='freitascodes.stacks', verbose_name='Stacks')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['project_type', 'name'],
            },
        ),
    ]
