# Generated by Django 5.1.3 on 2024-11-13 03:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Projeto')),
                ('project_type', models.IntegerField(choices=[(1, 'Projeto'), (2, 'Biblioteca')], default=1, verbose_name='Tipo de Projeto')),
                ('repo_name', models.CharField(help_text='Link do Github', max_length=500, verbose_name='Name do Repositório')),
                ('avaliable_at', models.CharField(help_text='Link do Projeto em produção ou biblioteca no PYPI por exemplo.', max_length=500, verbose_name='Disponível em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está Disponível?')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['project_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Tecnologia')),
                ('skillicon_name', models.CharField(help_text='Disponível em https://github.com/tandpfun/skill-icons?tab=readme-ov-file#icons-list', verbose_name='Name do Skill Icon')),
            ],
            options={
                'verbose_name': 'Stack',
                'verbose_name_plural': 'Stacks',
                'ordering': ['stack_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TipoStacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Stack',
                'verbose_name_plural': 'Tipos de Stacks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Imagem')),
                ('arquivo', models.ImageField(upload_to='projetos', verbose_name='Imagem')),
                ('ordem', models.IntegerField(default=5, help_text='Quanto maior, maior a prioridade na ordenação', verbose_name='Ordem da imagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está Disponível?')),
                ('projeto', models.ForeignKey(help_text='Projeto associado', on_delete=django.db.models.deletion.CASCADE, to='freitascodes.projetos', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
                'ordering': ['projeto__name', 'ordem', 'ativo'],
            },
        ),
        migrations.AddField(
            model_name='projetos',
            name='stacks',
            field=models.ManyToManyField(help_text='Stacks utilizadas ou disponível para estas stacks', to='freitascodes.stacks', verbose_name='Stacks'),
        ),
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Link do Github', max_length=500, verbose_name='Name do Repositório')),
                ('descricao', models.TextField(verbose_name='Descrição do Curso/Certificado')),
                ('avaliable_at', models.CharField(help_text='Link do Projeto em produção ou biblioteca no PYPI por exemplo.', max_length=2000, verbose_name='Disponível em')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='certificados', verbose_name='Arquivo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está Disponível?')),
                ('stacks', models.ManyToManyField(help_text='Stacks associadas', to='freitascodes.stacks', verbose_name='Stacks')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['nome', 'ativo'],
            },
        ),
        migrations.AddField(
            model_name='stacks',
            name='stack_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='freitascodes.tipostacks', verbose_name='Tipo de Stack'),
        ),
    ]
