# Generated by Django 5.1.3 on 2024-11-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freitascodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='avaliable_at',
            field=models.CharField(blank=True, help_text='Link do Certificado Online.', max_length=2000, null=True, verbose_name='Disponível em'),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='nome',
            field=models.CharField(max_length=500, verbose_name='Nome do Certificado'),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='stacks',
            field=models.ManyToManyField(help_text='Stacks associadas ao certificado.', to='freitascodes.stacks', verbose_name='Stacks'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='avaliable_at',
            field=models.CharField(blank=True, help_text='Link do Projeto em produção ou biblioteca no PYPI por exemplo.', max_length=500, null=True, verbose_name='Disponível em'),
        ),
    ]
