# Generated by Django 5.1.3 on 2024-11-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freitascodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Link do Github', max_length=500, verbose_name='Name do Repositório')),
                ('descricao', models.TextField(verbose_name='Descrição do Curso/Certificado')),
                ('avaliable_at', models.CharField(help_text='Link do Projeto em produção ou biblioteca no PYPI por exemplo.', max_length=2000, verbose_name='Disponível em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está Disponível?')),
                ('stacks', models.ManyToManyField(help_text='Stacks associadas', to='freitascodes.stacks', verbose_name='Stacks')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['nome', 'ativo'],
            },
        ),
    ]
