# Generated by Django 5.1.3 on 2025-01-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freitascodes', '0002_alter_certificados_avaliable_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stacks',
            name='skillicon_name',
            field=models.CharField(verbose_name='Link do Icone da Skill'),
        ),
    ]
