name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud credentials
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_BASE64" | base64 --decode > /tmp/gcp_key.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcp_key.json"

      - name: Configure SSH key
        run: |
          echo "$GCP_SSH_KEY" > /tmp/gcp_ssh_key
          chmod 600 /tmp/gcp_ssh_key

      - name: Create .env file
        run: |
          echo "CONTAINER_BACKEND_NAME=${{ secrets.CONTAINER_BACKEND_NAME }}" > .env
          echo "CONTAINER_DB_NAME=${{ secrets.CONTAINER_DB_NAME }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env

      - name: Transfer .env file to VM
        run: |
          scp -o StrictHostKeyChecking=no -i /tmp/gcp_ssh_key .env humildadevps@$GCP_VM_IP:/home/humildadevps/freitascodes/.env

      - name: Deploy to Google Cloud VM
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/gcp_ssh_key humildadevps@$GCP_VM_IP << 'EOF'
            cd /home/humildadevps/freitascodes
            git checkout .
            git pull origin main -f
            rm -rf /home/humildadevps/freitascodes/venv/
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt --no-cache
            python manage.py migrate freitascodes
            rm -rf /home/humildadevps/freitascodes/freitascodes/static/*
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
          EOF

      - name: Clean up SSH key and credentials
        run: |
          rm -f /tmp/gcp_ssh_key
          rm -f /tmp/gcp_key.json
        if: always()

    env:
      GCP_VM_IP: ${{ secrets.GCP_VM_IP }}
      GCP_SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
      GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
