name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud credentials
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_BASE64" | base64 --decode > /tmp/gcp_key.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcp_key.json"

      - name: Configure SSH key
        run: |
          echo "$GCP_SSH_KEY" > /tmp/gcp_ssh_key
          chmod 600 /tmp/gcp_ssh_key
      - name: Set environment variables in app.yaml and .env on VM
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/gcp_ssh_key humildadevps@$GCP_VM_IP << EOF
            rm /home/humildadevps/freitascodes/.env
            echo "CONTAINER_BACKEND_NAME=${{ secrets.CONTAINER_BACKEND_NAME }}" >> /home/humildadevps/freitascodes/.env
            echo "CONTAINER_DB_NAME=${{ secrets.CONTAINER_DB_NAME }}" >> /home/humildadevps/freitascodes/.env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> /home/humildadevps/freitascodes/.env
            echo "DB_USER=${{ secrets.DB_USER }}" >> /home/humildadevps/freitascodes/.env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> /home/humildadevps/freitascodes/.env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> /home/humildadevps/freitascodes/.env
          EOF
      - name: Deploy to Google Cloud VM
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/gcp_ssh_key humildadevps@$GCP_VM_IP << 'EOF'
            cd /home/humildadevps/freitascodes
            git checkout .
            git pull origin main -f
            rm -rf /home/humildadevps/freitascodes/venv/
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt --no-cache
            sleep 10
            python manage.py migrate freitascodes
            rm -rf /home/humildadevps/freitascodes/freitascodes/static/*
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
          EOF

      - name: Clean up SSH key and credentials
        run: |
          rm -f /tmp/gcp_ssh_key
          rm -f /tmp/gcp_key.json
        if: always()

    env:
      GCP_VM_IP: ${{ secrets.GCP_VM_IP }}
      GCP_SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
      GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}