name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud credentials
        run: |
          # Decodifica a chave de autenticação em base64 e salva como um arquivo JSON
          echo "$GOOGLE_APPLICATION_CREDENTIALS_BASE64" | base64 --decode > /tmp/gcp_key.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcp_key.json"

      - name: Configure SSH key
        run: |
          echo "$GCP_SSH_KEY" > /tmp/gcp_ssh_key
          chmod 600 /tmp/gcp_ssh_key

      - name: Deploy to Google Cloud VM
        run: |
          # Conecta à VM e executa os comandos
          ssh -o StrictHostKeyChecking=no -i /tmp/gcp_ssh_key humildadevps@$GCP_VM_IP << 'EOF'
            cd /home/humildadevps/freitascodes
            git pull origin main
            source venv/bin/activate
            python manage.py migrate
            python manage.py collectstatic --noinput
          EOF

      - name: Clean up SSH key and credentials
        run: |
          rm -f /tmp/gcp_ssh_key
          rm -f /tmp/gcp_key.json
        if: always()

    env:
      GCP_VM_IP: ${{ secrets.GCP_VM_IP }}
      GCP_SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
      GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}