name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >-
          --health-cmd="pg_isready -U ${{ secrets.DB_USER }}" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
        ports:
          - 5432:5432

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: steel-wharf-441413-f8
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
          
      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json
          
      - name: Set environment variables in app.yaml
        run: |
          echo "runtime: python311" > app.yaml
          echo "env_variables:" >> app.yaml
          echo "  CONTAINER_BACKEND_NAME: ${{ secrets.CONTAINER_BACKEND_NAME }}" >> app.yaml
          echo "  CONTAINER_DB_NAME: ${{ secrets.CONTAINER_DB_NAME }}" >> app.yaml
          echo "  DB_NAME: ${{ secrets.DB_NAME }}" >> app.yaml
          echo "  DB_USER: ${{ secrets.DB_USER }}" >> app.yaml
          echo "  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}" >> app.yaml
          echo "  DB_HOST: ${{ secrets.DB_HOST }}" >> app.yaml

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies in virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Django migrations
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: "127.0.0.1"  # Host local para conexão com o serviço PostgreSQL
        run: |
          source venv/bin/activate
          python manage.py migrate

      - name: Collect static files
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: "127.0.0.1"
        run: |
          source venv/bin/activate
          python manage.py collectstatic --noinput

      - name: Deploy to Google App Engine
        run: gcloud app deploy