name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute commands on Google Cloud VM
      env:
        GCP_VM_IP: ${{ secrets.GCP_VM_IP }}
        GCP_SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
      run: |
        # Configura a chave SSH temporariamente
        echo "$GCP_SSH_KEY" > /tmp/gcp_key
        chmod 600 /tmp/gcp_key

        # Conecta na VM e executa os comandos de atualização e configuração
        ssh -o StrictHostKeyChecking=no -i /tmp/gcp_key your_vm_user@$GCP_VM_IP << 'EOF'
          # Navega até o diretório do projeto
          cd /caminho/do/seu/projeto

          # Faz o pull do código mais recente
          git pull origin main

          # Executa migrações do Django
          source venv/bin/activate
          python manage.py migrate

          # Executa o collectstatic
          python manage.py collectstatic --noinput
        EOF

      cleanup: |
        rm -f /tmp/gcp_key