jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud credentials
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure SSH key
        run: |
          echo "$GCP_SSH_KEY" > /tmp/gcp_key
          chmod 600 /tmp/gcp_key

      - name: Deploy to Google Cloud VM
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/gcp_key humildadevps@$GCP_VM_IP << 'EOF'
            cd /home/humildadevps/freitascodes
            git pull origin main
            source venv/bin/activate
            python manage.py migrate
            python manage.py collectstatic --noinput
          EOF

      - name: Clean up SSH key
        run: |
          rm -f /tmp/gcp_key
        if: always()

    env:
      GCP_VM_IP: ${{ secrets.GCP_VM_IP }}
      GCP_SSH_KEY: ${{ secrets.GCP_SSH_KEY }}